name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by Cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.16.0-chrome113-ff116
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB: ${{ secrets.GITHUB_TOKEN }}

  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.16.0-chrome113-ff116
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: yarn install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB: ${{ secrets.GITHUB_TOKEN }}

  cypress-e2e-firefox:
    needs: cypress-e2e-chrome
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.16.0-chrome113-ff116
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: yarn install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB: ${{ secrets.GITHUB_TOKEN }}
