name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by Cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Ajustar permissões do Cypress
        run: |
          mkdir -p /github/home/.cache/Cypress
          sudo chown -R 1001:1001 /github/home/.cache/Cypress

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_CACHE_FOLDER: /github/home/.cache/Cypress
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB: ${{ secrets.GITHUB_TOKEN }}

  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Ajustar permissões do Cypress
        run: |
          mkdir -p /github/home/.cache/Cypress
          sudo chown -R 1001:1001 /github/home/.cache/Cypress

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: yarn install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_CACHE_FOLDER: /github/home/.cache/Cypress
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB: ${{ secrets.GITHUB_TOKEN }}

  cypress-e2e-firefox:
    needs: cypress-e2e-chrome
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Ajustar permissões do Cypress
        run: |
          mkdir -p /github/home/.cache/Cypress
          sudo chown -R 1001:1001 /github/home/.cache/Cypress

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: yarn install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_CACHE_FOLDER: /github/home/.cache/Cypress
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB: ${{ secrets.GITHUB_TOKEN }}
