name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      spec:
         description: Run by cypress command line
         default: TaskFinal/cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container: 
        image: cypress/browser:node18.12.0-chrome103-ff107
        options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install-command: yarn install
          browser: electron
          record: false
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}

  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
        image: cypress/browser:node18.12.0-chrome103-ff107
        options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install-command: yarn install
          browser: chrome
          record: false
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}

  cypress-e2e-firefox:
    needs: cypress-e2e-chrome
    runs-on: ubuntu-latest
    container: 
        image: cypress/browser:node18.12.0-chrome103-ff107
        options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install-command: yarn install
          browser: firefox
          record: false
          group: UI Firefox
          spec: ${{ github.event.inputs.spec }}name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      spec:
         description: Run by cypress command line
         default: TaskFinal/cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container: 
        image: cypress/browser:node18.12.0-chrome103-ff107
        options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install-command: yarn install
          browser: electron
          record: false
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}

  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
        image: cypress/browser:node18.12.0-chrome103-ff107
        options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install-command: yarn install
          browser: chrome
          record: false
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}

  cypress-e2e-firefox:
    needs: cypress-e2e-chrome
    runs-on: ubuntu-latest
    container: 
        image: cypress/browser:node18.12.0-chrome103-ff107
        options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install-command: yarn install
          browser: firefox
          record: false
          group: UI Firefox
          spec: ${{ github.event.inputs.spec }}
